name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    services:
      api-solid-pg:
        image: bitnami/postgresql
        ports:
          - 5442:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run E2E tests
        run: npm run test:e2e
        env:
          JWT_SECRET: testing-secret
          DATABASE_URL: "postgresql://docker:docker@localhost:5442/apisolid?schema=public"